port: 9000
default_page_size: 20
env: "develop"
public_dir: "./public"
database:
  - driver: "sqlite"
    file: "d:/github/sqlite3.db"
redis:
  - host: "localhost:6379"
    password: ""
    db: 0 